version: '3'
services:
  backend:
    image: morerao/vollo-backend:v1
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5433
  
  frontend:
    image: morerao/vollo-frontend:v1
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
  
  database:
    build: ./database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
