version: '3.8'
services:
  backend:
    image: morerao/vollo-backend:prod
    ports:
      - "8128:8128"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=vollo_db
      - DB_USER=postgres
      - DB_PASS=Shikimori2031.
    volumes:
      - backend_data:/app
    networks:
      - vollo_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    image: morerao/vollo-frontend:prod
    ports:
      - "8129:8129"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8128
    volumes:
      - frontend_data:/app
    networks:
      - vollo_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  database:
    image: postgres:13
    ports:
      - "8130:5432"
    environment:
      - POSTGRES_DB=vollo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shikimori2031.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vollo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  vollo_network:
    driver: bridge

volumes:
  postgres_data:
  backend_data:
  frontend_data:
