version: '3.8'
services:
  backend:
    image: morerao/vollo-backend:${BACKEND_TAG:-latest}
    ports:
      - "8128:8128"
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      # ...outras variáveis...
  frontend:
    image: morerao/vollo-frontend:${FRONTEND_TAG:-latest}
    ports:
      - "8129:8129"
    environment:
      - BACKEND_URL=http://backend:8128
  database:
    image: postgres:13
    # ...configuração do banco...
    ports:
      - "8130:5432"
    environment:
      - POSTGRES_DB=${DB_NAME:-vollo_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=Shikimori2031.
      - DB_PASS=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vollo_network

volumes:
  postgres_data:

networks:
  vollo_network:
    driver: bridge