version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: morerao/vollo-backend:${BACKEND_TAG:-latest}
    ports:
      - "8128:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=vollo_db
      - DB_USER=postgres
      - DB_PASS=Shikimori2031.
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - vollo_network

  frontend:
    image: morerao/vollo-frontend:${FRONTEND_TAG:-latest}
    build: ./frontend
    ports:
      - "8129:3001"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - vollo_network

  database:
    image: postgres:13
    ports:
      - "8130:5432"
    environment:
      - POSTGRES_DB=vollo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shikimori2031.
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vollo_network

networks:
  vollo_network:
    driver: bridge

volumes:
  postgres_data:
