name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Test
        run: |
          docker-compose build
          docker-compose run backend npm test
      
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: 201.23.3.86
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/projeto-vollo
            git pull origin main
            docker-compose up -d
