name: Debug Workflow

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
      
      - name: Informações do sistema
        run: |
          echo "Versão do Docker:"
          docker --version
          echo "Versão do Docker Compose:"
          docker-compose --version
          echo "Versão do Node:"
          node --version
          echo "Versão do npm:"
          npm --version
      
      - name: Verificar conteúdo dos Dockerfiles
        run: |
          echo "Dockerfile Backend:"
          cat ./backend/Dockerfile
          echo -e "\n\nDockerfile Frontend:"
          cat ./frontend/Dockerfile
      
      - name: Verificar package.json
        run: |
          echo "Backend package.json:"
          cat ./backend/package.json
          echo -e "\n\nFrontend package.json:"
          cat ./frontend/package.json
      
      - name: Tentar build com docker-compose
        run: |
          docker-compose config
          docker-compose build
