name: CI/CD Pipeline Vollo
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Instalar dependências Backend
      working-directory: ./backend
      run: npm install
    
    - name: Instalar dependências Frontend
      working-directory: ./frontend
      run: npm install
    
    - name: Rodar testes Backend
      working-directory: ./backend
      run: npm test
    
    - name: Build e Push Backend
      run: |
        docker build -t morerao/vollo-backend:${{ github.sha }} ./backend
        docker push morerao/vollo-backend:${{ github.sha }}
    
    - name: Build e Push Frontend
      run: |
        docker build -t morerao/vollo-frontend:${{ github.sha }} ./frontend
        docker push morerao/vollo-frontend:${{ github.sha }}
    
    - name: Análise SonarQube
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy em Servidor Remoto
      uses: appleboy/ssh-action@master
      with:
        host: 201.23.3.86
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /path/projeto-vollo
          
          # Atualizar imagens
          docker pull morerao/vollo-backend:${{ github.sha }}
          docker pull morerao/vollo-frontend:${{ github.sha }}
          
          # Atualizar docker-compose.yml para usar novas imagens
          sed -i "s/image: morerao\/vollo-backend:.*/image: morerao\/vollo-backend:${{ github.sha }}/g" docker-compose.yml
          sed -i "s/image: morerao\/vollo-frontend:.*/image: morerao\/vollo-frontend:${{ github.sha }}/g" docker-compose.yml
          
          # Baixar e reiniciar serviços
          docker-compose pull
          docker-compose down
          docker-compose up -d
